Modify cache buster. (#810)
I've seen several intermittent FMC test failures in GHA that don't make
sense, and I've been unable to reproduce with ASAN/TSAN/running the
tests thousands of times locally. I'd like to rule out a corrupt GHA
cache as the cause...

```
---- test_fht_info stdout ----
thread 'test_fht_info' panicked at 'called `Result::unwrap()` on an `Err` value: MailboxCmdFailed(0)', fmc/tests/test_rtalias.rs:93:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_pcr_log stdout ----
thread 'test_pcr_log' panicked at 'called `Result::unwrap()` on an `Err` value: MailboxCmdFailed(0)', fmc/tests/test_rtalias.rs:132:59
```